'use strict';

// all available html tags
const tagRegex = /<(\bh1\b|\bh2\b|\bh3\b|\bh4\b|\bh5\b|\bh6\b|\bstrong\b|\bblockquote\b|\ba\b|\bp\b|\bul\b|\bol\b|\bli\b|\bhr\b|\bem\b|\bpre\b|\bcode\b|\btable\b|\bth\b|\btd\b|\btr\b)/g;

/**
 * Convert html tags to contain a css modules class variable
 * @description showdown js custom extension - https://github.com/showdownjs/showdown
 * @tutorial https://github.com/showdownjs/showdown/wiki/extensions#filter-property
 * @returns {Array} - showdownjs extension
 */
let classy = () => {
  return [{
    type: 'output', // output extensions (or modifiers) alter the HTML output generated by showdown
    filter: (text) => { // filter property should be a function that acts as a callback
      return text.replace(tagRegex, (match, tag) => {
        return `<${tag} class="{$ styles.${tag} $}"`;
      });
    }
  }];
};

module.exports = classy;
